version: '3.1'

services:
  vitals-monitor-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vitals_monitor_root_pwd
      MYSQL_DATABASE: db_vitals_monitor
      MYSQL_USER: apl.vitals_monitor
      MYSQL_PASSWORD: vitals_monitor_user_pwd